apiVersion: v1
kind: Service
metadata:
  name: helloworld-app
  namespace: training
spec:
  type: NodePort
  selector:
    app: helloworld-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31001  

