apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  namespace: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-app
  template:
    metadata:
      labels:
        app: helloworld-app
    spec:
      containers:
      - name: helloworld-container
        image: harshi39/harshitha-site:v1
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: DB_PASSWORD
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: APP_COLOR
        volumeMounts:
        - name: myapp-storage        
          mountPath: /usr/share/data
      volumes:
      - name: myapp-storage
        persistentVolumeClaim:
          claimName: myapp-pvc

